const KEY="auditflow_v2_offline";
const $=s=>document.querySelector(s), uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
let data=load(),activeCaseId=null,modalContext=null;
function load(){try{const d=JSON.parse(localStorage.getItem(KEY)||localStorage.getItem("auditflow_offline_v1"));if(d?.cases)return d}catch(e){}return{cases:[]}}
function esc(s=""){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function save(){localStorage.setItem(KEY,JSON.stringify(data));renderAll()}
function active(){return data.cases.find(x=>x.id===activeCaseId)||data.cases[0]}
function toast(t){let e=$("#toast");e.textContent=t;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),1800)}
function empty(t){return `<div class="empty">${t}</div>`}
function riskClass(r){return r==="高"?"high":r==="中"?"medium":"low"}
function ensureCase(){if(!data.cases.length)data.cases.push({id:uid(),name:"我的第一個審計案件",number:"",agency:"",period:"",status:"進行中",events:[],issues:[],findings:[],evidence:[],procedures:[]});data.cases.forEach(c=>{["events","issues","findings","evidence","procedures"].forEach(k=>c[k]??=[])});activeCaseId||=data.cases[0].id}
function renderSelector(){let a=active();$("#caseSelector").innerHTML=data.cases.map(c=>`<option value="${c.id}" ${c.id===a.id?"selected":""}>${esc(c.name)}</option>`).join("")}
function renderDashboard(){let c=active(),issues=c.issues,events=c.events;$("#statEvents").textContent=events.length;$("#statIssues").textContent=issues.length;$("#statHigh").textContent=issues.filter(i=>i.risk==="高").length;$("#statOpen").textContent=issues.filter(i=>i.status!=="已結案").length;
$("#caseInfo").innerHTML=[["案件名稱",c.name],["案件編號",c.number||"—"],["受查單位",c.agency||"—"],["查核期間",c.period||"—"],["案件狀態",`<span class="badge ${c.status==="進行中"?"open":"closed"}">${esc(c.status)}</span>`]].map(x=>`<div class="info-row"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join("");
let recent=[...events].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5);$("#recentEvents").innerHTML=recent.length?recent.map(e=>`<div class="compact-item"><strong>${esc(e.title)}</strong><small>${esc(e.date)}　${esc(e.category||"一般")}</small></div>`).join(""):empty("尚無大事記紀錄");
let h=issues.filter(i=>i.risk==="高").length,m=issues.filter(i=>i.risk==="中").length,l=issues.filter(i=>i.risk==="低").length,t=Math.max(issues.length,1);$("#riskSummary").innerHTML=`<div class="meta-line"><span>🔴 高 ${h}</span><span>🟡 中 ${m}</span><span>🟢 低 ${l}</span></div><div class="risk-bar"><div class="r-high" style="width:${h/t*100}%"></div><div class="r-medium" style="width:${m/t*100}%"></div><div class="r-low" style="width:${l/t*100}%"></div></div>`;
let op=issues.filter(i=>i.status!=="已結案");$("#followups").innerHTML=op.length?op.map(i=>`<div class="compact-item"><strong>${esc(i.title)}</strong><small><span class="badge ${riskClass(i.risk)}">${i.risk}風險</span>　${esc(i.status)}</small></div>`).join(""):empty("目前沒有待追蹤問題")}
function renderTimeline(){let list=[...active().events].sort((a,b)=>b.date.localeCompare(a.date));$("#timelineList").innerHTML=list.length?list.map(e=>`<article class="timeline-item"><div class="item-meta">${esc(e.date)}｜${esc(e.category)}｜重要性：${esc(e.importance)}</div><strong>${esc(e.title)}</strong><p>${esc(e.description)}</p><div class="item-actions"><button onclick="editEvent('${e.id}')">編輯</button><button onclick="deleteItem('events','${e.id}')">刪除</button></div></article>`).join(""):empty("尚無紀錄")}
function renderIssues(){let c=active(),list=c.issues;$("#issueList").innerHTML=list.length?list.map(i=>{let whys=[1,2,3,4,5].filter(n=>i["why"+n]).map(n=>`<div class="why-row"><b>Why ${n}</b><span>${esc(i["why"+n])}</span></div>`).join("");let cats=["人員","制度","流程","法規","預算","資料","管理","其他"].filter(x=>i["fish_"+x]).map(x=>`<span class="badge open">${esc(x)}：${esc(i["fish_"+x])}</span>`).join("");return `<article class="issue-card"><div class="meta-line"><span class="badge ${riskClass(i.risk)}">${esc(i.risk)}風險</span><span class="badge ${i.status==="已結案"?"closed":"open"}">${esc(i.status)}</span></div><h3>${esc(i.title)}</h3><p>${esc(i.description)}</p><div class="analysis-box"><h4>5 Why 分析</h4>${whys||"尚未填寫"}<h4>根本原因</h4><div class="root-cause">${esc(i.rootCause||"尚未填寫")}</div>${cats?`<h4>魚骨分析</h4><div class="relation">${cats}</div>`:""}</div><div class="item-actions"><button onclick="editIssue('${i.id}')">編輯</button><button onclick="deleteItem('issues','${i.id}')">刪除</button></div></article>`}).join(""):empty("尚無問題分析資料")}
function renderFindings(){let list=active().findings;$("#findingList").innerHTML=list.length?list.map(f=>`<article class="finding"><h3>${esc(f.title)}</h3><dl><dt>問題描述</dt><dd>${esc(f.problem)}</dd><dt>查核方法／證據</dt><dd>${esc(f.evidence)}</dd><dt>法規或依據</dt><dd>${esc(f.basis)}</dd><dt>改善建議</dt><dd>${esc(f.recommendation)}</dd></dl><div class="item-actions"><button onclick="editFinding('${f.id}')">編輯</button><button onclick="deleteItem('findings','${f.id}')">刪除</button></div></article>`).join(""):empty("尚無查核發現")}
function issueOptions(value=""){return `<option value="">未關聯問題</option>`+active().issues.map(i=>`<option value="${i.id}" ${i.id===value?"selected":""}>${esc(i.title)}</option>`).join("")}
function renderEvidence(){let list=active().evidence;$("#evidenceList").innerHTML=list.length?list.map(e=>{let issue=active().issues.find(i=>i.id===e.issueId);return `<article class="finding"><div class="meta-line"><strong>${esc(e.code)}</strong><span class="badge open">${esc(e.type)}</span></div><h3>${esc(e.title)}</h3><p>${esc(e.description)}</p><div class="issue-ref">關聯問題：${issue?esc(issue.title):"未設定"}</div><div class="item-actions"><button onclick="editEvidence('${e.id}')">編輯</button><button onclick="deleteItem('evidence','${e.id}')">刪除</button></div></article>`}).join(""):empty("尚無證據資料")}
function renderProcedures(){let list=active().procedures;$("#procedureList").innerHTML=list.length?list.map(p=>{let issue=active().issues.find(i=>i.id===p.issueId);return `<article class="finding"><div class="meta-line"><span class="badge ${p.status==="已完成"?"low":p.status==="執行中"?"medium":"open"}">${esc(p.status)}</span><span class="issue-ref">${issue?esc(issue.title):"未關聯問題"}</span></div><h3>${esc(p.title)}</h3><dl><dt>查核目的</dt><dd>${esc(p.objective)}</dd><dt>查核程序</dt><dd>${esc(p.steps)}</dd><dt>所需資料</dt><dd>${esc(p.documents)}</dd><dt>查核結果</dt><dd>${esc(p.result)}</dd></dl><div class="item-actions"><button onclick="editProcedure('${p.id}')">編輯</button><button onclick="deleteItem('procedures','${p.id}')">刪除</button></div></article>`}).join(""):empty("尚無查核程序")}
function renderWorkpaper(){let c=active(), html=`<div class="wp-title"><h2>審計工作底稿</h2><div>${esc(c.name)}</div></div><div class="wp-section"><h3>一、案件基本資料</h3><table class="wp-table"><tr><th>案件編號</th><td>${esc(c.number)}</td><th>受查單位</th><td>${esc(c.agency)}</td></tr><tr><th>查核期間</th><td colspan="3">${esc(c.period)}</td></tr></table></div>`;c.issues.forEach((i,n)=>{let ev=c.evidence.filter(e=>e.issueId===i.id),ps=c.procedures.filter(p=>p.issueId===i.id);html+=`<div class="wp-section"><h3>問題 ${n+1}：${esc(i.title)}</h3><h4>問題描述</h4><div class="wp-text">${esc(i.description)}</div><h4>5 Why 根本原因分析</h4>${[1,2,3,4,5].filter(x=>i["why"+x]).map(x=>`<div>Why ${x}：${esc(i["why"+x])}</div>`).join("")}<div class="root-cause"><b>根本原因：</b>${esc(i.rootCause)}</div><h4>查核程序</h4><table class="wp-table"><tr><th>程序</th><th>狀態</th><th>結果</th></tr>${ps.map(p=>`<tr><td>${esc(p.steps)}</td><td>${esc(p.status)}</td><td>${esc(p.result)}</td></tr>`).join("")||"<tr><td colspan='3'>尚無資料</td></tr>"}</table><h4>相關證據</h4><table class="wp-table"><tr><th>編號</th><th>名稱</th><th>說明</th></tr>${ev.map(e=>`<tr><td>${esc(e.code)}</td><td>${esc(e.title)}</td><td>${esc(e.description)}</td></tr>`).join("")||"<tr><td colspan='3'>尚無資料</td></tr>"}</table></div>`});$("#workpaperContent").innerHTML=html}
function renderAll(){ensureCase();renderSelector();renderDashboard();renderTimeline();renderIssues();renderEvidence();renderProcedures();renderFindings();renderWorkpaper()}
function openModal(title,html,ctx){modalContext=ctx;$("#modalTitle").textContent=title;$("#modalForm").innerHTML=html;$("#modal").classList.remove("hidden")}
function closeModal(){$("#modal").classList.add("hidden")}
function field(n,l,v="",type="text",cls=""){return type==="textarea"?`<div class="field ${cls}"><label>${l}</label><textarea name="${n}">${esc(v)}</textarea></div>`:`<div class="field ${cls}"><label>${l}</label><input type="${type}" name="${n}" value="${esc(v)}"></div>`}
function select(n,l,v,opts,cls=""){return `<div class="field ${cls}"><label>${l}</label><select name="${n}">${opts.map(o=>`<option ${o===v?"selected":""}>${o}</option>`).join("")}</select></div>`}
function formWrap(f){return `<div class="form-grid">${f}</div><div class="form-actions"><button type="button" onclick="closeModal()">取消</button><button class="primary">儲存</button></div>`}
function caseForm(c={}){openModal(c.id?"編輯案件":"新增案件",formWrap([field("name","案件名稱",c.name||"","text","full"),field("number","案件編號",c.number||""),field("agency","受查單位",c.agency||""),field("period","查核期間",c.period||""),select("status","案件狀態",c.status||"進行中",["進行中","暫停","已完成"])]),{type:"case",id:c.id})}
function eventForm(e={}){openModal(e.id?"編輯大事記":"新增大事記",formWrap([field("date","日期",e.date||new Date().toISOString().slice(0,10),"date"),select("category","分類",e.category||"查核",["案件啟動","查核","溝通","資料取得","證據","重要發現","其他"]),select("importance","重要性",e.importance||"中",["低","中","高","重大"]),field("title","事件標題",e.title||"","text","full"),field("description","事件內容",e.description||"","textarea","full")]),{type:"event",id:e.id})}
function issueForm(i={}){let fish=["人員","制度","流程","法規","預算","資料","管理","其他"].map(x=>field("fish_"+x,"魚骨："+x,i["fish_"+x]||"","text")).join("");openModal(i.id?"編輯問題分析":"新增問題分析",formWrap([field("title","問題標題",i.title||"","text","full"),field("description","問題描述",i.description||"","textarea","full"),select("category","問題分類",i.category||"制度",["人員","制度","流程","資料","預算","管理","法規","其他"]),select("risk","風險等級",i.risk||"中",["高","中","低"]),select("status","處理狀態",i.status||"待追蹤",["待追蹤","查核中","已處理","已結案"]),... [1,2,3,4,5].map(n=>field("why"+n,"Why "+n,i["why"+n]||"","text","full")),field("rootCause","根本原因",i.rootCause||"","textarea","full"),fish]),{type:"issue",id:i.id})}
function evidenceForm(e={}){openModal(e.id?"編輯證據":"新增證據",formWrap([field("code","證據編號",e.code||`E-${String(active().evidence.length+1).padStart(3,"0")}`),field("title","證據名稱",e.title||""),select("type","證據類型",e.type||"文件",["文件","函文","照片","現場紀錄","資料分析","其他"]),`<div class="field"><label>關聯問題</label><select name="issueId">${issueOptions(e.issueId)}</select></div>`,field("description","證據說明",e.description||"","textarea","full")]),{type:"evidence",id:e.id})}
function procedureForm(p={}){openModal(p.id?"編輯查核程序":"新增查核程序",formWrap([field("title","程序名稱",p.title||"","text","full"),`<div class="field"><label>關聯問題</label><select name="issueId">${issueOptions(p.issueId)}</select></div>`,select("status","執行狀態",p.status||"尚未執行",["尚未執行","執行中","已完成"]),field("objective","查核目的",p.objective||"","textarea","full"),field("steps","查核程序",p.steps||"","textarea","full"),field("documents","所需資料",p.documents||"","textarea","full"),field("result","查核結果",p.result||"","textarea","full")]),{type:"procedure",id:p.id})}
function findingForm(f={}){openModal(f.id?"編輯查核發現":"新增查核發現",formWrap([field("title","查核發現標題",f.title||"","text","full"),field("problem","問題描述",f.problem||"","textarea","full"),field("evidence","查核方法／證據",f.evidence||"","textarea","full"),field("basis","法規或依據",f.basis||"","textarea","full"),field("recommendation","改善建議",f.recommendation||"","textarea","full")]),{type:"finding",id:f.id})}
$("#modalForm").addEventListener("submit",e=>{e.preventDefault();let o=Object.fromEntries(new FormData(e.target)),c=active(),ctx=modalContext;if(ctx.type==="case"){if(ctx.id)Object.assign(data.cases.find(x=>x.id===ctx.id),o);else{data.cases.push({id:uid(),...o,events:[],issues:[],findings:[],evidence:[],procedures:[]});activeCaseId=data.cases.at(-1).id}}else{let key={event:"events",issue:"issues",finding:"findings",evidence:"evidence",procedure:"procedures"}[ctx.type],arr=c[key];ctx.id?Object.assign(arr.find(x=>x.id===ctx.id),o):arr.push({id:uid(),...o})}closeModal();save();toast("已儲存")})
window.closeModal=closeModal;$("#closeModal").onclick=closeModal;$("#modal").onclick=e=>{if(e.target.id==="modal")closeModal()};
$("#newCaseBtn").onclick=()=>caseForm();$("#editCaseBtn").onclick=()=>caseForm(active());$("#quickEventBtn").onclick=()=>eventForm();$("#addEventBtn").onclick=()=>eventForm();$("#addIssueBtn").onclick=()=>issueForm();$("#addFindingBtn").onclick=()=>findingForm();$("#addEvidenceBtn").onclick=()=>evidenceForm();$("#addProcedureBtn").onclick=()=>procedureForm();$("#caseSelector").onchange=e=>{activeCaseId=e.target.value;renderAll()};
document.querySelectorAll(".nav-btn").forEach(b=>b.onclick=()=>showView(b.dataset.view));document.querySelectorAll("[data-view-go]").forEach(b=>b.onclick=()=>showView(b.dataset.viewGo));function showView(v){document.querySelectorAll(".view").forEach(x=>x.classList.toggle("active",x.id===v));document.querySelectorAll(".nav-btn").forEach(x=>x.classList.toggle("active",x.dataset.view===v))}
window.editEvent=id=>eventForm(active().events.find(x=>x.id===id));window.editIssue=id=>issueForm(active().issues.find(x=>x.id===id));window.editFinding=id=>findingForm(active().findings.find(x=>x.id===id));window.editEvidence=id=>evidenceForm(active().evidence.find(x=>x.id===id));window.editProcedure=id=>procedureForm(active().procedures.find(x=>x.id===id));window.deleteItem=(key,id)=>{if(confirm("確定刪除？")){active()[key]=active()[key].filter(x=>x.id!==id);save()}};
$("#exportBtn").onclick=()=>{let b=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=`AuditFlow_V2_Backup_${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);toast("備份已匯出")};$("#importBtn").onclick=()=>$("#importFile").click();$("#importFile").onchange=async e=>{let f=e.target.files[0];if(!f)return;try{let p=JSON.parse(await f.text());if(!Array.isArray(p.cases))throw 0;if(confirm("匯入將覆蓋目前資料，確定嗎？")){data=p;activeCaseId=p.cases[0]?.id;save();toast("資料已還原")}}catch{x=0;alert("檔案格式不正確")}};$("#clearAllBtn").onclick=()=>{if(confirm("確定永久清除？")){data={cases:[]};activeCaseId=null;localStorage.removeItem(KEY);renderAll()}};
$("#printWorkpaperBtn").onclick=()=>window.print();renderAll();